artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://www.kaggle.com/datasets/paultimothymooney/chest-xray-pneumonia"
  local_data_file: artifacts/data_ingestion/raw_data